# Generated by Django 4.0.4 on 2022-04-17 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('price', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('sqft_living', models.FloatField()),
                ('sqft_lot', models.FloatField()),
                ('floors', models.IntegerField()),
                ('waterfront', models.BooleanField()),
                ('view', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('sqft_above', models.FloatField()),
                ('sqft_basement', models.FloatField()),
                ('yr_built', models.FloatField(verbose_name='year built')),
                ('yr_renovated', models.FloatField(verbose_name='year renovated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
            ],
            options={
                'db_table': 'home',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='service.home')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('statezip', models.TextField()),
                ('country', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
