# Generated by Django 4.0.4 on 2022-04-17 07:46

from django.db import migrations
from dateutil import parser
import pandas as pd


def seed_data(apps, schema_editor):
    Home = apps.get_model("service", "Home")
    Address = apps.get_model("service", "Address")

    data= pd.read_csv("./data0967ed6.csv")

    # print(data.price)
    for i, row in data.iterrows():
        # print('price', row.price)
        home = Home.objects.create(
            date = parser.parse(row.date),
            price=row.price,
            bedrooms=row.bedrooms,
            bathrooms=row.bathrooms,
            sqft_living = row.sqft_living,
            sqft_lot = row.sqft_lot,
            floors = row.floors,
            waterfront = row.waterfront,
            view = row['view'],
            condition = row.condition,
            sqft_above = row.sqft_above,
            sqft_basement = row.sqft_basement,
            yr_built = row.yr_built,
            yr_renovated = row.yr_renovated,
        )

        Address.objects.create(
            home=home,
            street=row.street,
            city = row.city,
            statezip = row.statezip,
            country = row.country,
        )

def unseed_data(apps, schema_editor):
    Home = apps.get_model("service", "Home")
    Address = apps.get_model("service", "Address")

    Address.objects.all().delete()
    Home.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data)
    ]
